---
openapi: 3.0.3
info:
  title: API for verifying Ethoca Alerts
  description: Ethoca Alert API
  termsOfService: https://kount.com/legal/terms-of-use
  contact:
    email: support@kount.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/yashshavi/finalTry/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://127.0.0.1:4010
  description: SwaggerHub API Auto Mocking
paths:
  /kff/ethoca/alerts:
    post:
      tags:
      - ethocaAlert
      summary: Posting ALerts
      description: Alert enpoint to post list of Alerts
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/EthocaAlertNotification'
      responses:
        "200":
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/EthocaAlertConfirmation'
components:
  schemas:
    EthocaAlertNotification:
      required:
      - Password
      - Username
      properties:
        Username:
          type: string
          description: Username for the client to authenticate the request
          example: ethocasystemidvtZpv8kpZTds5h6m
        Password:
          type: string
          description: Passord to authenticate the request
          example: system_password
        ConfirmedFraudAlerts:
          $ref: '#/components/schemas/FraudAlert'
        CustomerDisputeAlert:
          $ref: '#/components/schemas/DisputeAlert'
    FraudAlert:
      required:
      - Alert
      type: object
      properties:
        Alert:
          $ref: '#/components/schemas/FraudAlertFormat'
    DisputeAlert:
      required:
      - Alert
      type: object
      properties:
        Alert:
          $ref: '#/components/schemas/DisputeAlertFormat'
    FraudAlertFormat:
      required:
      - Age
      - AlertTimestamp
      - Amount
      - CardNumber
      - Currency
      - EthocaID
      - EthocaMerchantID
      - InitiatedBy
      - Issuer
      - Liability
      - MerchantDescriptor
      - MerchantName
      - PartnerMerchantID
      - TransactionTimestamp
      - TransactionType
      type: object
      properties:
        EthocaID:
          type: string
          description: Ethoca generated unique ID for the alert.
          example: 2L07DBRFGBDLIW7SH59V969JG
        AlertTimestamp:
          type: string
          description: The date and time the alert was created in the Ethoca system. It is sent in the integrators time zone
          format: date-time
          example: 2015-02-27T04:33:04.328Z
        Age:
          type: integer
          description: The age of the alert is the number of hours between the transaction date/time (authorisation date/time) and the AlertTimestamp
          example: 42
        Issuer:
          type: string
          description: The name of the card issuer.
          example: CARD_ISSUER
        CardNumber:
          type: string
          description: The card number. For CF, the card number is unmasked by default and can be masked if needed. Card numbers also appear masked if the issuer sends partial card data
          example: 800012******6824
        ARN:
          type: string
          description: Acquirer Reference Number (ARN) is a unique 23 digit number that tags a card transaction when it goes from the merchants bank (the acquiring bank) through the card scheme to the cardholder's bank (the issuer). It is only available for settled transactions.
          example: "98765432456789876345213"
        TransactionTimestamp:
          type: string
          description: This is the authorisation date/time for the transaction.
          format: date-time
          example: 2015-02-28T04:33:04.328Z
        MerchantDescriptor:
          type: string
          description: The merchant descriptor is the description as seen on the card holder’s statement
          example: ABC123 ONLINE
        EthocaMerchantID:
          type: integer
          description: A unique ID for each Ethoca merchants.
          example: 98765
        Amount:
          type: number
          description: Transaction amount
          format: double
          example: 352.99
        Currency:
          maxLength: 3
          type: string
          description: Currency for the transaction amount
          example: USD
        TransactionType:
          type: string
          description: The type of transaction
          enum:
          - keyed
          - swiped
          - e-commerce
          - unknown
        InitiatedBy:
          type: string
          description: Whether the transaction was initially identified by the card holder or the card issuer.
          enum:
          - issuer
          - cardholder
          - not_available
        Liability:
          type: string
          description: Whether it is a 3D Secure transaction or not. This element indicates which party is liable.
          enum:
          - "yes"
          - "no"
          - not_available
        authCode:
          type: string
          description: Optional 8 digit Authorization code
          example: "73536582"
        MerchantName:
          type: string
          description: The merchant name of the Ethoca member. For partners receiving alerts on behalf of merchants then this will be the Member Name for the merchant.
          example: ABC ONLINE
        PartnerMerchantID:
          type: string
          description: A unique ID for the merchant in the integrator / partner’s platform.
          example: "456789"
        MCC:
          type: integer
          description: Merchant Category Code – defines the industry to which the transaction belongs
          example: 4567
        Source:
          type: string
          description: This field indicates whether an alert was originated directly from an issuer, or from another source.
          example: 4567abc
    DisputeAlertFormat:
      required:
      - Age
      - AlertTimestamp
      - Amount
      - CardNumber
      - ChargebackAmount
      - ChargebackCurrency
      - ChargebackReasonCode
      - Currency
      - EthocaID
      - EthocaMerchantID
      - InitiatedBy
      - Issuer
      - Liability
      - MerchantDescriptor
      - MerchantName
      - PartnerMerchantID
      - TransactionId
      - TransactionTimestamp
      - TransactionType
      type: object
      properties:
        EthocaID:
          type: string
          description: Ethoca generated unique ID for the alert.
          example: 2L07DBRFGBDLIW7SH59V969JG
        AlertTimestamp:
          type: string
          description: The date and time the alert was created in the Ethoca system. It is sent in the integrators time zone
          format: date-time
          example: 2015-02-27T04:33:04.328Z
        Age:
          type: integer
          description: The age of the alert is the number of hours between the transaction date/time (authorisation date/time) and the AlertTimestamp
          example: 42
        Issuer:
          type: string
          description: The name of the card issuer.
          example: CARD_ISSUER
        CardNumber:
          type: string
          description: The card number. For CF, the card number is unmasked by default and can be masked if needed. Card numbers also appear masked if the issuer sends partial card data
          example: 800012******6824
        ARN:
          type: string
          description: Acquirer Reference Number (ARN) is a unique 23 digit number that tags a card transaction when it goes from the merchants bank (the acquiring bank) through the card scheme to the cardholder's bank (the issuer). It is only available for settled transactions.
          example: "98765432456789876345213"
        TransactionTimestamp:
          type: string
          description: This is the authorisation date/time for the transaction.
          format: date-time
          example: 2015-02-28T04:33:04.328Z
        MerchantDescriptor:
          type: string
          description: The merchant descriptor is the description as seen on the card holder’s statement
          example: ABC123 ONLINE
        EthocaMerchantID:
          type: integer
          description: A unique ID for each Ethoca merchants.
          example: 98765
        Amount:
          type: number
          description: Transaction amount
          format: double
          example: 352.99
        Currency:
          type: string
          description: Currency for the transaction amount
          example: USD
        TransactionType:
          type: string
          description: The type of transaction
          enum:
          - keyed
          - swiped
          - e-commerce
          - unknown
        InitiatedBy:
          type: string
          description: Whether the transaction was initially identified by the card holder or the card issuer.
          enum:
          - issuer
          - cardholder
          - not_available
        Liability:
          type: string
          description: Whether it is a 3D Secure transaction or not. This element indicates which party is liable.
          enum:
          - "yes"
          - "no"
          - not_available
        authCode:
          type: string
          description: Optional 8 digit Authorization code
          example: "73536582"
        MerchantName:
          type: string
          description: The merchant name of the Ethoca member. For partners receiving alerts on behalf of merchants then this will be the Member Name for the merchant.
          example: ABC ONLINE
        PartnerMerchantID:
          type: string
          description: A unique ID for the merchant in the integrator / partner’s platform.
          example: "456789"
        MCC:
          type: integer
          description: Merchant Category Code – defines the industry to which the transaction belongs
          example: 4567
        Source:
          type: string
          description: This field indicates whether an alert was originated directly from an issuer, or from another source.
          example: 4567abc
        TransactionId:
          type: string
          description: Transaction ID is a unique value that the card schemes assign to each transaction and return to the Acquirer in the Authorization Response. This value is maintained throughout the life cycle of the Transaction and all related transactions such as Reversals, Adjustments, Chargebacks etc.
          example: REF123
        ChargebackReasonCode:
          type: string
          description: The card scheme-specific chargeback reason code which indicates the cardholder’s reason for disputing the transaction.
          example: UNAU
        ChargebackAmount:
          type: number
          description: The chargeback amount for a transaction. The chargeback amount may be different from the transaction amount.
          format: double
          example: 352.99
        ChargebackCurrency:
          type: string
          description: The currency for the chargeback amount.
          example: USD
    EthocaAlertConfirmation:
      required:
      - Alert
      properties:
        Alert:
          $ref: '#/components/schemas/ConfirmAlert'
      xml:
        name: EthocaAlertConfirmation
    ConfirmAlert:
      required:
      - EthocaID
      - Status
      type: object
      properties:
        EthocaID:
          type: string
          description: Unique Ethoca ID for the alert updated
          example: 2L07DBRFGBDLIW7SH59V969JG
        Status:
          type: string
          description: The code indicating the outcome of the request
          enum:
          - received
          - retry
